trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'ddf71576-3ea7-4417-9f12-743b5912f938'
  imageRepository: 'backend'
  containerRegistry: 'ecommercecontainer.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/backend/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  name: 'docker-linux-agent'
  demands:
    - agent.name -equals Docker Agent - Linux  # Cambia esto por el nombre de tu agente si es distinto

stages:
# Etapa 1: Compilar el .jar con Gradle
- stage: Build_Jar
  displayName: "Compilar el .jar con Gradle"
  jobs:
    - job: GradleBuild
      displayName: "Compilar .jar"
      steps:
        - task: Gradle@3
          inputs:
            workingDirectory: 'backend'
            gradleWrapperFile: 'backend/gradlew'
            gradleOptions: '-Xmx1024m'
            tasks: build
            publishJUnitResults: false
        - script: ls -la backend/build/libs
          displayName: "Verificar que se generó el .jar"
        - task: CopyFiles@2
          inputs:
            contents: '**/build/libs/*.jar'
            targetFolder: '$(Build.ArtifactStagingDirectory)'

        - publish: $(Build.ArtifactStagingDirectory)
          artifact: drop
        
# Etapa 2: Construir imagen Docker y subir a ACR
- stage: Build_And_Push_Image
  displayName: "Construir imagen y subir a ACR"
  dependsOn: Build_Jar
  jobs:
    - job: DockerBuild
      displayName: "Docker Build & Push"
      pool:
        name: 'docker-linux-agent'
        demands:
          - agent.name -equals Docker Agent - Linux
      steps:
        - download: current
          artifact: drop
        - script: ls -la $(Pipeline.Workspace)/drop/backend/build/libs/
          displayName: "Verificar que el .jar esta drop"
        - script: |
            mkdir -p backend/build/libs
            cp $(Pipeline.Workspace)/drop/backend/build/libs/*.jar backend/build/libs/
          displayName: 'Copiar .jar al contexto backend/build/libs'
        - task: Docker@2
          displayName: "Construir y subir imagen a ACR"
          inputs:
            command: buildAndPush
            repository: $(imageRepository)
            dockerfile: $(dockerfilePath)
            containerRegistry: $(dockerRegistryServiceConnection)
            tags: |
              $(tag)
- stage: Deploy_Web_App
  displayName: Deploy container to web app
  dependsOn: Build_And_Push_Image
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Azure subscription 1(7286d3c8-dcc9-4c06-8b82-b1ae61ed12f0)'
        appName: 'ecommerceBackend'
        containers: 'ecommercecontainer.azurecr.io/backend:$(tag)'
