version: '3.8'

services:

  frontend:

    build: frontend

    ports:

      - 3000:3000

    volumes:
      - ./frontend/src:/app/src

  backend:

    build: backend

    ports:

      - 8080:8080

    depends_on:
      - db

  db:
    build: db/mysql-init
    ports:
      - 3306:3306
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: ecommerce  # Opcional: nombre de la base de datos que deseas crear
    MYSQL_USER: ecommerce # Opcional: nombre de un usuario adicional
    MYSQL_PASSWORD: ecommerce
    volumes:
      - ./db/mysql-init:/docker-entrypoint-initdb
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    